# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f926b2ea3c7cf23ecd074cb8804444aa0c074257441915aeab0a87648e338278c7cf2ed92cc6effdf47c42f9bea6f1b16a8f2f72dd016cd7c32229c92504da0

test:
  secret_key_base: a191b2ad49d4d70f187d68e511d10256104d9e1013efbf0f9a2cf5c7baae65ecafec5a29cc7e7df774532f76880aba56e85f5d2752ee44b0ed3ebc0770d24610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
